binary_sensor:
# 8 inputs to the board.  use them to toggle relay output.
# make these internal only by default.  Override if needed.
  - platform: gpio
#    name: "input 1"
    id: input1
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - switch.toggle: relay1
    
  - platform: gpio
#    name: "input 2"
    id: input2
    pin: 
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay2
    filters:
      - delayed_on_off: 10ms
    
  - platform: gpio
#    name: "input 3"
    id: input3
    pin: 
      number: GPIO6
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay3
    filters:
      - delayed_on_off: 10ms
    
  - platform: gpio
#    name: "input 4"
    id: input4
    pin: 
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay4
    filters:
      - delayed_on_off: 10ms
    
  - platform: gpio
#    name: "input 5"
    id: input5
    pin: 
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay5
    filters:
      - delayed_on_off: 10ms

  - platform: gpio
#    name: "input 6"
    id: input6
    pin: 
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay6
    filters:
      - delayed_on_off: 10ms
    
  - platform: gpio
#    name: "input 7"
    id: input7
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay7
    filters:
      - delayed_on_off: 10ms
    
  - platform: gpio
#    name: "input 8"
    id: input8
    pin: 
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: relay8
    filters:
      - delayed_on_off: 10ms
    
