# common wifi for Van automation stuff and home development.

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 10
  # second network
    - ssid: !secret van_ssid
      password: !secret van_password
      priority: 20

  # Enable AP when WiFi connection fails
  ap:
    ssid: ${device_name}
    password: !secret hotspot_password

# on_connect:


#captive_portal:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s
#  encryption:
#    key: !secret api_encryption_key

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret ota_password

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_adx
    ssid:
      id: ap_name

